Ensure bundler version works with trusty Ruby version
** Context **
The following error happens when running docker build with the
Dockerfile.trusty build file. This could be addressed by changing the OS,
upgrading ruby or downgrading bundler.
```
ERROR:  Error installing bundler:
	bundler requires Ruby version >= 2.3.0.
```

** Decision **
The goal is to get fpm builds working with docker. Changing the OS across the
estate or upgrading ruby for trusty will take considerably more effort than
downgrading the bundler version. So, ensure that bundler is a compatible
version by setting to `-v "< 2"`.